name: CI main
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }}

    runs-on: ubuntu-latest
    strategy:
      matrix:
        # only versions of node 22 and above are supported
        node: ['22.x']

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Enable Corepack
        run: corepack enable

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - name: Run install
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: install # will run `yarn install` command

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build
